name: feast
type: python

up:
  - python: 3.7.9
  - custom:
      name: Upgrade pip
      met?: pip install --upgrade pip
      meet: "true"
  - custom:
      name: Install pre-commit
      met?: pip list | grep -v pre-commit
      meet: pip install pre-commit && pre-commit install
  - gcloud:
      components:
          - core
  - custom:
      name: "Authenticate with GCloud"
      met?: gcloud auth application-default print-access-token &> /dev/null
      meet: gcloud auth application-default login
  - custom:
     name: Google Cloud AI Platform Project
     met?: gcloud config get-value project | grep -q "shopify-data-ml-platform-exp"
     meet: gcloud config set project shopify-data-ml-platform-exp

commands:
  format:
    run: |
      make format-python
      make lint-python
    desc: 'Format and lint all Python files'
  
  test:
    run: make test-python
    desc: 'Test all Python files'